var ytplayer;
(function(f){f.fn.vPlayer=function(c){c=f.extend({type:"normal",autoplay:"off",videoWidth:0,videoHeight:0,constrols_out_opacity:0,constrols_normal_opacity:0.9,design_scrubbarWidth:-201,insideGallery:!1,design_skin:"skin_default",design_background_offsetw:0},c);this.each(function(){function s(){b.find(".preview").hide();e.children().eq(0).css("visibility","hidden");e.children().eq(1).css("visibility","hidden");e.children().eq(2).css("visibility","visible");e.children().eq(3).css("visibility","visible");
"normal"==c.type&&d.play();"youtube"==c.type&&d.playVideo();b.children(".video-description").animate({opacity:0},500);t=!0}function z(){e.children().eq(0).css("visibility","visible");e.children().eq(1).css("visibility","visible");e.children().eq(2).css("visibility","hidden");e.children().eq(3).css("visibility","hidden");"normal"==c.type&&d.pause();"youtube"==c.type&&d.pauseVideo();b.children(".video-description").animate({opacity:1},500);t=!1}function A(){function a(p,e){b.css({width:p,height:e});
jQuery(d).css({width:p,height:e});b.find(".background").css({width:p+parseInt(c.design_background_offsetw)});b.find(".preview").children().eq(0).css({width:p,height:e});g.css({width:p,height:e});is_ie8()&&g.css({position:"absolute",top:0,left:0});scrubbar=b.find(".scrubbar").children();scrubbar.eq(0).width(p+c.design_scrubbarWidth);E=parseInt(g.find(".infoText").css("left"));parseInt(g.find(".infoText").css("top"))}function F(a){var e=b.find(".volumecontrols").children();0<=a&&("normal"==c.type&&
(d.volume=a),"youtube"==c.type&&d.setVolume(100*a));e.eq(2).width(a*e.eq(1).width());null!=localStorage&&localStorage.setItem("volumeIndex",a)}function o(a){var a=Math.round(a),b=0;if(0<a){for(;59<a;)b++,a-=60;return""+((10>b?"0":"")+b+":"+(10>a?"0":"")+a)}return"00:00"}null!=localStorage&&(G=null===localStorage.getItem("volumeIndex")?1:localStorage.getItem("volumeIndex"));b.append('<div class="controls"></div>');g=b.find(".controls");g.css("opacity",c.constrols_normal_opacity);0==i&&(i=f(d).width(),
j=f(d).height());q=i;r=j;b.css({width:i,height:j});void 0!=b.attr("data-videoTitle")&&(b.append('<div class="video-description"></div>'),b.children(".video-description").append('<div class="video-title">'+b.attr("data-videoTitle")+"</div>"),""!=B&&b.children(".video-description").append('<div class="video-subdescription">'+B+"</div>"),b.find(".video-subdescription").css("width",0.7*i));"absolute"!=b.css("position")&&b.css("position","relative");"normal"==c.type&&f(d).css({position:"absolute","background-color":"#000000"});
g.append('<div class="background"></div>');g.append('<div class="playcontrols"></div>');g.append('<div class="scrubbar"></div>');g.append('<div class="timetext"></div>');g.append('<div class="volumecontrols"></div>');g.append('<div class="fscreencontrols"></div>');void 0!=jQuery(d).attr("data-description")&&(g.append('<div class="info"></div>'),g.append('<div class="infoText"></div>'));void 0!=b.attr("data-img")&&b.append('<div class="preview"><img src="'+b.attr("data-img")+'"/></div>');H=b.find(".info");
l=b.find(".infoText");void 0!=jQuery(d).attr("data-description")?l.append('<div class="rounded descriptionText">'+jQuery(d).attr("data-description")+"</div>"):(l.hide(),H.hide());b.find(".info").click(function(){l=b.find(".infoText");0==l.css("opacity")?(l.animate({left:"0",opacity:"0"},{queue:!1,duration:0}),l.animate({left:E,opacity:"1"},{queue:!1,duration:700})):l.animate({left:q,opacity:"0"},{queue:!1,duration:700})});e=b.find(".playcontrols");e.append('<div class="playSimple"></div>');e.append('<div class="playHover"></div>');
e.append('<div class="stopSimple"></div>');e.append('<div class="stopHover"></div>');e.click(function(){u=!1;"normal"==c.type&&d.paused&&(u=!0);"youtube"==c.type&&2==d.getPlayerState()&&(u=!0);is_ie8()?C?(s(),C=!1):(z(),C=!0):u?s():z()});e.hover(function(){e.children().eq(1).animate({opacity:1},{queue:!1,duration:300});e.children().eq(3).animate({opacity:1},{queue:!1,duration:300})},function(){e.children().eq(1).animate({opacity:0},{queue:!1,duration:300});e.children().eq(3).animate({opacity:0},{queue:!1,
duration:300})});scrubbar=b.find(".scrubbar");scrubbar.append('<div class="scrub-bg"></div>');scrubbar.append('<div class="scrub"></div>');scrubbar.click(function(a){scrubbar=b.find(".scrubbar");!1==t?z():s();"normal"==c.type&&(m=d.duration,d.currentTime=(a.pageX-scrubbar.offset().left)/scrubbar.children().eq(0).width()*m);"youtube"==c.type&&(m=d.getDuration(),d.seekTo((a.pageX-scrubbar.offset().left)/scrubbar.children().eq(0).width()*m))});setInterval(function(){scrubbar=b.find(".scrubbar");"normal"==
c.type&&(m=d.duration,v=d.currentTime);"youtube"==c.type&&(m=d.getDuration(),v=d.getCurrentTime());k=v/m*scrubbar.children().eq(0).width();scrubbar.children().eq(1).width(k);b.find(".timetext").html('<font color="#FFFFFF" size="1px">'+o(v)+'</font><font color="gray" size="1px">/'+o(m)+"</font>")},100);h=b.find(".volumecontrols");h.append('<div class="volumeicon"></div>');h.append('<div class="volume_static"></div>');h.append('<div class="volume_active"></div>');h.append('<div class="volume_cut"></div>');
b.find(".volumecontrols").click(function(a){h=b.find(".volumecontrols").children();0<=a.pageX-h.eq(1).offset().left?(k=a.pageX-h.eq(1).offset().left,h.eq(2).css("visibility","visible"),h.eq(3).css("visibility","hidden"),F(k/h.eq(1).width())):"hidden"==h.eq(3).css("visibility")?(w=d.volume,"normal"==c.type&&(d.volume=0),"youtube"==c.type&&d.setVolume(0),h.eq(3).css("visibility","visible"),h.eq(2).css("visibility","hidden")):(console.log(w),"normal"==c.type&&(d.volume=w),"youtube"==c.type&&d.setVolume(w),
h.eq(3).css("visibility","hidden"),h.eq(2).css("visibility","visible"))});n=b.find(".fscreencontrols");n.append('<div class="full"></div>');n.append('<div class="fullHover"></div>');n.click(function(){q=f(window).width();r=f(window).height();0==x?(x=1,b.css({position:"fixed","z-index":9999,left:"0px",top:"0px",width:"100%",height:"100%"}),jQuery("body").css("overflow","hidden"),a(q,r),!0==c.insideGallery&&jQuery(this).parent().parent().parent().parent().parent().turnFullscreen()):(x=0,b.css({position:"relative",
"z-index":"auto",left:"0px",top:"0px",width:i,height:j}),jQuery("body").css("overflow","auto"),a(i,j),!0==c.insideGallery&&jQuery(this).parent().parent().parent().parent().parent().turnNormalscreen())});n.hover(function(){n.children().eq(1).animate({opacity:1},{queue:!1,duration:300})},function(){n.children().eq(1).animate({opacity:0},{queue:!1,duration:300})});a(i,j);F(G);"on"==D&&s();b.mouseout(function(){g.animate({opacity:c.constrols_out_opacity},{queue:!1,duration:200})});b.mouseover(function(){g.animate({opacity:c.constrols_normal_opacity},
{queue:!1,duration:200})});f(window).resize(function(){1===x&&(q=f(window).width(),r=f(window).height(),a(q,r))})}var b,g,i,j,q,r,d,k=0,x=0,o,w,G,E,t=!1,D="off",h,n,e,H,l,u=!1,C=!0,m=0,v=0,I="",y="",J="",B="";b=jQuery(this);f(this)[0].getAttribute("id");D=c.autoplay;i=c.videoWidth;j=c.videoHeight;if(b.hasClass("vplayer-tobe")){var a=b;a.removeClass("vplayer-tobe");a.addClass("vplayer");a.addClass(c.design_skin);0<a.find(".videoDescription").length&&(B=a.find(".videoDescription").html(),a.find(".videoDescription").remove());
I=a.attr("data-type");J=a.attr("data-src");y=a.attr("data-sourceflash");void 0==a.attr("data-sourceflash")&&(y=a.attr("data-sourcemp4"));if(is_ie8()){a.addClass("vplayer-ie8");"youtube"!=I?a.append('<div><object type="application/x-shockwave-flash" data="preview.swf" width="'+i+'" height="'+j+'" id="flashcontent" style="visibility: visible;"><param name="movie" value="preview.swf"><param name="menu" value="false"><param name="allowScriptAccess" value="always"><param name="scale" value="noscale"><param name="allowFullScreen" value="true"><param name="wmode" value="opaque"><param name="flashvars" value="video='+
y+'"></object></div>'):(c.type="youtube",a.children().remove(),k="ytplayer"+J,a.append('<iframe width="'+i+'" height="'+j+'" src="http://www.youtube.com/embed/'+a.attr("data-src")+'" frameborder="0" allowfullscreen></iframe>'),a.attr("data-ytid",k));return}if(is_ios()){a.append("<video controls preload></video>");a.children().eq(0).attr("width",i);a.children().eq(0).attr("height",j);"youtube"!=a.attr("data-type")?("ie8/flash"==c.type,void 0!=a.attr("data-sourcemp4")&&a.children().eq(0).append('<source src="'+
a.attr("data-sourcemp4")+'" type="video/mp4"/>')):(c.type="youtube",a.children().remove(),k="ytplayer"+a.attr("data-src"),a.append('<iframe width="'+i+'" height="'+j+'" src="http://www.youtube.com/embed/'+a.attr("data-src")+'" frameborder="0" allowfullscreen></iframe>'));return}!is_ie8()&&!is_ios()&&(a.append("<video controls preload></video>"),"youtube"!=a.attr("data-type")?(void 0!=a.attr("data-sourcemp4")&&(a.children().eq(0).append('<source src="'+a.attr("data-sourcemp4")+'" type="video/mp4"/>'),
is_ie9()&&a.html('<video controls preload><source src="'+a.attr("data-sourcemp4")+'" type="video/mp4"/></video>')),void 0!=a.attr("data-sourceogg")&&a.children().eq(0).append('<source src="'+a.attr("data-sourceogg")+'" type="video/ogg"/>'),void 0!=a.attr("data-sourcewebm")&&a.children().eq(0).append('<source src="'+a.attr("data-sourcewebm")+'" type="video/webm"/>'),void 0!=a.attr("data-sourceflash")&&!(f.browser.msie&&8<f.browser.version)&&a.children().eq(0).append('<object type="application/x-shockwave-flash" data="preview.swf" width="'+
i+'" height="'+j+'" id="flashcontent" style="visibility: visible;"><param name="movie" value="preview.swf"><param name="menu" value="false"><param name="allowScriptAccess" value="always"><param name="scale" value="noscale"><param name="allowFullScreen" value="true"><param name="wmode" value="opaque"><param name="flashvars" value="video='+y+'"></object>')):(c.type="youtube",a.children().remove(),k="ytplayer"+a.attr("data-src"),a.append('<object type="application/x-shockwave-flash" data="http://www.youtube.com/apiplayer?enablejsapi=1&version=3&playerapiid='+
k+'" width="'+i+'" height="'+j+'" id="'+k+'" style="visibility: visible;"><param name="movie" value="http://www.youtube.com/apiplayer?enablejsapi=1&version=3"><param name="menu" value="false"><param name="allowScriptAccess" value="always"><param name="scale" value="noscale"><param name="allowFullScreen" value="true"><param name="wmode" value="opaque"><param name="flashvars" value=""></object>'),a.attr("data-ytid",k)))}0==b.css("opacity")&&b.animate({opacity:1},1E3);"normal"==c.type?(d=b.children().eq(0)[0],
d.controls=!1):d=b.children().eq(0)[0];"on"==D&&(t=!0);o=setInterval(function(){if("youtube"==c.type&&d.getPlayerState){if(is_ie8()){clearInterval(o);setTimeout(A,1E3);return}-1<d.getPlayerState()&&(clearInterval(o),A())}"normal"==c.type&&3<=Number(d.readyState)&&(clearInterval(o),A())},50);epauseMovie=function(a){if(!is_ios()){var b=a.find(".playcontrols").children();b.eq(0).css("visibility","visible");b.eq(1).css("visibility","visible");b.eq(2).css("visibility","hidden");b.eq(3).css("visibility",
"hidden");0<a.find("video").length&&a.find("video")[0].pause();void 0!=a.attr("data-ytid")&&document.getElementById(a.attr("data-ytid")).pauseVideo()}}})}})(jQuery);function onYouTubePlayerReady(f){ytplayer=document.getElementById(f);ytplayer.addEventListener("onStateChange","onytplayerStateChange");f=f.substr(8);ytplayer.loadVideoById(f);ytplayer.pauseVideo()}function onytplayerStateChange(){}
function is_ios(){return-1!=navigator.platform.indexOf("iPhone")||-1!=navigator.platform.indexOf("iPod")||-1!=navigator.platform.indexOf("iPad")}function is_ie9(){return $.browser.msie&&9==parseInt($.browser.version)?!0:!1}function is_ie8(){return $.browser.msie&&9>parseInt($.browser.version)?!0:!1};